### ISSUE TITLE
Support Node >= 8.10 (UnhandledPromiseRejectionWarning)

### ISSUE THREAD

**Issue by n1try** [n1try/mininote#5]
- https://nodejs.org/dist/latest-v8.x/docs/api/deprecations.html#deprecations_dep0018_unhandled_promise_rejections

```
Listening at http://localhost:3000
(node:21948) UnhandledPromiseRejectionWarning: Error: Exited with code 3
at ChildProcess.cp.once.code (/home/lisbeth/Documents/mininote/mininote-frontend/node_modules/opn/index.js:84:13)
at Object.onceWrapper (events.js:317:30)
at emitTwo (events.js:126:13)
at ChildProcess.emit (events.js:214:7)
at maybeClose (internal/child_process.js:925:16)
at Socket.stream.socket.on (internal/child_process.js:346:11)
at emitOne (events.js:116:13)
at Socket.emit (events.js:211:7)
at Pipe._handle.close [as _onclose] (net.js:567:12)
(node:21948) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:21948) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by jellesmedts** [comment]
I weirdly just had this error on my system, I'll post what I did, maybe it's helpful
clean ubuntu server 17.10 (VBox), HOST
    $ install nvm via script
    $ nvm install 9.8.0
    $ npm install -g @angular/cli
    $ ng serve --open
the --open is what got me this exact error.
hope it helps

**Comment by ashwamegh** [comment]
@n1try Is there anyone working on this?

**Comment by n1try** [comment]
@ashwamegh No, I don't think so.

**Comment by ashwamegh** [comment]
@n1try I will be working on this then 👍

**Comment by n1try** [comment]
Can't reproduce this anymore.
Recommended Node version is 10.x anyway.
